stages:
  - smoke-test

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

smoke-test:
  stage: smoke-test
  script:
    - echo "Runner is OK"
    - echo "Branch: ${CI_COMMIT_REF_NAME}"
    - echo "Pipeline source: ${CI_PIPELINE_SOURCE}"
    - date
    - uname -a
