# Шаблон зашифрованного секрета (SealedSecret) для вашей игры.
# Для создания зашифрованного секрета запустите команду:
# kubeseal --format=yaml --cert=pub-cert.pem < k8s/app/squirrel/squirrel-secrets.yaml > k8s/app/squirrel/squirrel-sealed-secrets.yaml
# После этого удалите исходный k8s/app/squirrel/squirrel-secrets.yaml и закоммитьте полученный squirrel-sealed-secrets.yaml.

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: squirrel-secrets
  namespace: game
spec:
  encryptedData:
    # Здесь будут зашифрованные данные, сгенерированные утилитой kubeseal
    SECRET_KEY: "ЗАШИФРОВАНО"
    POSTGRES_DB: "ЗАШИФРОВАНО"
    POSTGRES_USER: "ЗАШИФРОВАНО"
    POSTGRES_PASSWORD: "ЗАШИФРОВАНО"
    POSTGRES_HOST: "ЗАШИФРОВАНО"
    POSTGRES_PORT: "ЗАШИФРОВАНО"
    DATABASE_URL: "ЗАШИФРОВАНО"
    REDIS_URL: "ЗАШИФРОВАНО"
    BOT_TOKEN: "ЗАШИФРОВАНО"
