apiVersion: v1
kind: Secret
metadata:
  name: squirrel-secrets
  namespace: game
type: Opaque
stringData:
  # App
  SECRET_KEY: a9c7e4c4b9e6d9f1a2f5b8e0d3c6a4f9e1b7c2a8d0f6e9b3c4a1d5e8f7c6b2
  # Postgres
  POSTGRES_DB: squirrel
  POSTGRES_USER: squirrel
  POSTGRES_PASSWORD: supersecret
  POSTGRES_HOST: postgres-postgresql
  POSTGRES_PORT: "5432"

  DATABASE_URL: postgresql://squirrel:supersecret@postgres-postgresql:5432/squirrel

  # Redis
  REDIS_URL: redis://redis-master:6379
  BOT_TOKEN: 6908948780:AAGkxyA6rn4nnVsbHqsOF9FE_vxJZ0EWdNc
