FROM rust:1.88.0-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    build-essential \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# sqlx-cli нужен только здесь
RUN cargo install sqlx-cli --no-default-features --features postgres

WORKDIR /app

COPY migrations ./migrations
COPY .sqlx .sqlx

CMD ["sqlx", "database", "reset"]
# CMD ["sqlx", "migrate", "run"]
